<?php
/**
 * PickupShippingOption
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API introduction
 *
 * ### URL for API requests  `https://api.paazl.com/`  ### Optional keys  Some of the optional key-value pairs have a default value. Where this is the case, the default values will be indicated.  You can leave out optional keys from requests. If you leave out an optional key, it will not be included in the response concerned.  ### Paazl authentication  Paazl uses a three-legged OAuth 2.0 authentication process in which the API Secret (private key) is only known to the webshop. Webshop customers never have access to that key. However, they do have access the API Key (public key). See the online help article titled \"Authentication & Authorization\" for an explanation of how to generate these keys in the Paazl web app.  In Swagger, you authorize a call using the Authorize button. After clicking this button, you enter a string with either the format \"Bearer api_key\" or the format \"Bearer api_key:api_secret\" depending on the endpoint method concerned.  #### Calls requiring \"Bearer api_key\":  &#8226; POST shippingOptions  &#8226; POST pickupLocations  &#8226; POST checkout  Example:`\"Bearer sI3flYhflh\"`   #### Calls requiring \"Bearer api_key:api_secret\":  &#8226; POST token  &#8226; GET checkout  &#8226; POST order  &#8226; PUT order  &#8226; PATCH order  &#8226; DELETE order  Example:`\"Bearer sI3flYhflh:sdHlHkyunLKsoI94luilIlndD\"`
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PickupShippingOption Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PickupShippingOption implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PickupShippingOption';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'carrier' => '\OpenAPI\Client\Model\Carrier',
        'delivery_dates' => '\OpenAPI\Client\Model\DeliveryDate[]',
        'delivery_window' => '\OpenAPI\Client\Model\DeliveryWindow',
        'description' => 'string',
        'estimated_delivery_range' => '\OpenAPI\Client\Model\EstimatedDeliveryRange',
        'identifier' => 'string',
        'name' => 'string',
        'rate' => 'float',
        'tags' => 'string[]',
        'network' => 'string',
        'needs_customer_number' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'carrier' => null,
        'delivery_dates' => null,
        'delivery_window' => null,
        'description' => null,
        'estimated_delivery_range' => null,
        'identifier' => null,
        'name' => null,
        'rate' => null,
        'tags' => null,
        'network' => null,
        'needs_customer_number' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'carrier' => 'carrier',
        'delivery_dates' => 'deliveryDates',
        'delivery_window' => 'deliveryWindow',
        'description' => 'description',
        'estimated_delivery_range' => 'estimatedDeliveryRange',
        'identifier' => 'identifier',
        'name' => 'name',
        'rate' => 'rate',
        'tags' => 'tags',
        'network' => 'network',
        'needs_customer_number' => 'needsCustomerNumber'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'carrier' => 'setCarrier',
        'delivery_dates' => 'setDeliveryDates',
        'delivery_window' => 'setDeliveryWindow',
        'description' => 'setDescription',
        'estimated_delivery_range' => 'setEstimatedDeliveryRange',
        'identifier' => 'setIdentifier',
        'name' => 'setName',
        'rate' => 'setRate',
        'tags' => 'setTags',
        'network' => 'setNetwork',
        'needs_customer_number' => 'setNeedsCustomerNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'carrier' => 'getCarrier',
        'delivery_dates' => 'getDeliveryDates',
        'delivery_window' => 'getDeliveryWindow',
        'description' => 'getDescription',
        'estimated_delivery_range' => 'getEstimatedDeliveryRange',
        'identifier' => 'getIdentifier',
        'name' => 'getName',
        'rate' => 'getRate',
        'tags' => 'getTags',
        'network' => 'getNetwork',
        'needs_customer_number' => 'getNeedsCustomerNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const TAGS_PACK_STATION = 'PACK_STATION';
    const TAGS_SAME_DAY = 'SAME_DAY';
    const TAGS_FLEX_DELIVERY = 'FLEX_DELIVERY';
    const TAGS_CASH_ON_DELIVERY = 'CASH_ON_DELIVERY';
    const TAGS_INSURANCE = 'INSURANCE';
    const TAGS_SIGNATURE_REQUIRED = 'SIGNATURE_REQUIRED';
    const TAGS_AT_NEIGHBOURS = 'AT_NEIGHBOURS';
    const TAGS_NOT_AT_NEIGHBOURS = 'NOT_AT_NEIGHBOURS';
    const TAGS_RETURN_ON_FAILURE = 'RETURN_ON_FAILURE';
    const TAGS_DATE_PREFERENCE = 'DATE_PREFERENCE';
    const TAGS_TWENTYFOUR_SEVEN = 'TWENTYFOUR_SEVEN';
    const TAGS_NOTIFY_RECEIVER = 'NOTIFY_RECEIVER';
    const TAGS_SUNDAY_SORTING = 'SUNDAY_SORTING';
    const TAGS_AGE_CHECK = 'AGE_CHECK';
    const TAGS_ID_CHECK = 'ID_CHECK';
    const TAGS_CLIMATE_COMPENSATION = 'CLIMATE_COMPENSATION';
    const TAGS_DANGEROUS_GOODS = 'DANGEROUS_GOODS';
    const TAGS_RETURN_TO_SENDER = 'RETURN_TO_SENDER';
    const TAGS_NO_PROOF_OF_DELIVERY = 'NO_PROOF_OF_DELIVERY';
    const TAGS_PERISHABLE = 'PERISHABLE';
    const NETWORK_CARRIER = 'CARRIER';
    const NETWORK_STORE = 'STORE';
    const NETWORK_ALL = 'ALL';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTagsAllowableValues()
    {
        return [
            self::TAGS_PACK_STATION,
            self::TAGS_SAME_DAY,
            self::TAGS_FLEX_DELIVERY,
            self::TAGS_CASH_ON_DELIVERY,
            self::TAGS_INSURANCE,
            self::TAGS_SIGNATURE_REQUIRED,
            self::TAGS_AT_NEIGHBOURS,
            self::TAGS_NOT_AT_NEIGHBOURS,
            self::TAGS_RETURN_ON_FAILURE,
            self::TAGS_DATE_PREFERENCE,
            self::TAGS_TWENTYFOUR_SEVEN,
            self::TAGS_NOTIFY_RECEIVER,
            self::TAGS_SUNDAY_SORTING,
            self::TAGS_AGE_CHECK,
            self::TAGS_ID_CHECK,
            self::TAGS_CLIMATE_COMPENSATION,
            self::TAGS_DANGEROUS_GOODS,
            self::TAGS_RETURN_TO_SENDER,
            self::TAGS_NO_PROOF_OF_DELIVERY,
            self::TAGS_PERISHABLE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getNetworkAllowableValues()
    {
        return [
            self::NETWORK_CARRIER,
            self::NETWORK_STORE,
            self::NETWORK_ALL,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['carrier'] = isset($data['carrier']) ? $data['carrier'] : null;
        $this->container['delivery_dates'] = isset($data['delivery_dates']) ? $data['delivery_dates'] : null;
        $this->container['delivery_window'] = isset($data['delivery_window']) ? $data['delivery_window'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['estimated_delivery_range'] = isset($data['estimated_delivery_range']) ? $data['estimated_delivery_range'] : null;
        $this->container['identifier'] = isset($data['identifier']) ? $data['identifier'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['rate'] = isset($data['rate']) ? $data['rate'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['network'] = isset($data['network']) ? $data['network'] : null;
        $this->container['needs_customer_number'] = isset($data['needs_customer_number']) ? $data['needs_customer_number'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getNetworkAllowableValues();
        if (!is_null($this->container['network']) && !in_array($this->container['network'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'network', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets carrier
     *
     * @return \OpenAPI\Client\Model\Carrier|null
     */
    public function getCarrier()
    {
        return $this->container['carrier'];
    }

    /**
     * Sets carrier
     *
     * @param \OpenAPI\Client\Model\Carrier|null $carrier carrier
     *
     * @return $this
     */
    public function setCarrier($carrier)
    {
        $this->container['carrier'] = $carrier;

        return $this;
    }

    /**
     * Gets delivery_dates
     *
     * @return \OpenAPI\Client\Model\DeliveryDate[]|null
     */
    public function getDeliveryDates()
    {
        return $this->container['delivery_dates'];
    }

    /**
     * Sets delivery_dates
     *
     * @param \OpenAPI\Client\Model\DeliveryDate[]|null $delivery_dates Contains delivery date objects.
     *
     * @return $this
     */
    public function setDeliveryDates($delivery_dates)
    {
        $this->container['delivery_dates'] = $delivery_dates;

        return $this;
    }

    /**
     * Gets delivery_window
     *
     * @return \OpenAPI\Client\Model\DeliveryWindow|null
     */
    public function getDeliveryWindow()
    {
        return $this->container['delivery_window'];
    }

    /**
     * Sets delivery_window
     *
     * @param \OpenAPI\Client\Model\DeliveryWindow|null $delivery_window delivery_window
     *
     * @return $this
     */
    public function setDeliveryWindow($delivery_window)
    {
        $this->container['delivery_window'] = $delivery_window;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The contents of the `details` field for localized shipping option names you have configured in your Paazl web app account under *Settings>Paazl Perfect>Shipping options*.
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets estimated_delivery_range
     *
     * @return \OpenAPI\Client\Model\EstimatedDeliveryRange|null
     */
    public function getEstimatedDeliveryRange()
    {
        return $this->container['estimated_delivery_range'];
    }

    /**
     * Sets estimated_delivery_range
     *
     * @param \OpenAPI\Client\Model\EstimatedDeliveryRange|null $estimated_delivery_range estimated_delivery_range
     *
     * @return $this
     */
    public function setEstimatedDeliveryRange($estimated_delivery_range)
    {
        $this->container['estimated_delivery_range'] = $estimated_delivery_range;

        return $this;
    }

    /**
     * Gets identifier
     *
     * @return string|null
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param string|null $identifier A shipping option's Paazl code. You will find a list of the identifiers of the shipping options available to your webshop in your webshop account under *Settings>Account>Overview of shipping options*.
     *
     * @return $this
     */
    public function setIdentifier($identifier)
    {
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the shipping option as it appears in the Paazl Sell widget. This can have one of three values, in order of ascending priority:  1.  The Paazl \"default description\" for a shipping option (hard-coded in Paazl)  2.  The (customized) \"description\" of a shipping option (configured by [Paazl Customer Support](mailto:support@paazl.com))  3.  The localized name of a shipping option (you can configure this in the Paazl web app under *Settings>Paazl Perfect>Shipping options*.)
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets rate
     *
     * @return float|null
     */
    public function getRate()
    {
        return $this->container['rate'];
    }

    /**
     * Sets rate
     *
     * @param float|null $rate The shipping rate defined for the shipping option concerned in you webshop's delivery matrix.
     *
     * @return $this
     */
    public function setRate($rate)
    {
        $this->container['rate'] = $rate;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags Codes that are used to filter returned shipping options for display.
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $allowedValues = $this->getTagsAllowableValues();
        if (!is_null($tags) && array_diff($tags, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'tags', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets network
     *
     * @return string|null
     */
    public function getNetwork()
    {
        return $this->container['network'];
    }

    /**
     * Sets network
     *
     * @param string|null $network Specifies what type(s) of pickup locations you want Paazl to send you:  &#8226; \"CARRIER\": carrier pickup location  &#8226; \"STORE\": click &amp; collect pickup location  &#8226; \"ALL\": both types of pickup location
     *
     * @return $this
     */
    public function setNetwork($network)
    {
        $allowedValues = $this->getNetworkAllowableValues();
        if (!is_null($network) && !in_array($network, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'network', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['network'] = $network;

        return $this;
    }

    /**
     * Gets needs_customer_number
     *
     * @return bool|null
     */
    public function getNeedsCustomerNumber()
    {
        return $this->container['needs_customer_number'];
    }

    /**
     * Sets needs_customer_number
     *
     * @param bool|null $needs_customer_number If the shipping option concerned delivers to a DHL PackStation, this element will be set to `true`.
     *
     * @return $this
     */
    public function setNeedsCustomerNumber($needs_customer_number)
    {
        $this->container['needs_customer_number'] = $needs_customer_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


