<?php
/**
 * ShippingOptionRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API introduction
 *
 * ### URL for API requests  `https://api.paazl.com/`  ### Optional keys  Some of the optional key-value pairs have a default value. Where this is the case, the default values will be indicated.  You can leave out optional keys from requests. If you leave out an optional key, it will not be included in the response concerned.  ### Paazl authentication  Paazl uses a three-legged OAuth 2.0 authentication process in which the API Secret (private key) is only known to the webshop. Webshop customers never have access to that key. However, they do have access the API Key (public key). See the online help article titled \"Authentication & Authorization\" for an explanation of how to generate these keys in the Paazl web app.  In Swagger, you authorize a call using the Authorize button. After clicking this button, you enter a string with either the format \"Bearer api_key\" or the format \"Bearer api_key:api_secret\" depending on the endpoint method concerned.  #### Calls requiring \"Bearer api_key\":  &#8226; POST shippingOptions  &#8226; POST pickupLocations  &#8226; POST checkout  Example:`\"Bearer sI3flYhflh\"`   #### Calls requiring \"Bearer api_key:api_secret\":  &#8226; POST token  &#8226; GET checkout  &#8226; POST order  &#8226; PUT order  &#8226; PATCH order  &#8226; DELETE order  Example:`\"Bearer sI3flYhflh:sdHlHkyunLKsoI94luilIlndD\"`
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ShippingOptionRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShippingOptionRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShippingOptionRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'consignee_country_code' => 'string',
        'consignee_postal_code' => 'string',
        'consignor_country_code' => 'string',
        'consignor_postal_code' => 'string',
        'delivery_date_options' => '\OpenAPI\Client\Model\DeliveryDateOptions',
        'include_external_delivery_dates' => 'bool',
        'limit' => 'int',
        'locale' => 'string',
        'number_of_processing_days' => 'int',
        'shipment_parameters' => '\OpenAPI\Client\Model\ShipmentParameters',
        'sorting_model' => '\OpenAPI\Client\Model\SortingModel',
        'tags' => 'string[]',
        'token' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'consignee_country_code' => null,
        'consignee_postal_code' => null,
        'consignor_country_code' => null,
        'consignor_postal_code' => null,
        'delivery_date_options' => null,
        'include_external_delivery_dates' => null,
        'limit' => 'int32',
        'locale' => null,
        'number_of_processing_days' => 'int32',
        'shipment_parameters' => null,
        'sorting_model' => null,
        'tags' => null,
        'token' => 'uuid'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'consignee_country_code' => 'consigneeCountryCode',
        'consignee_postal_code' => 'consigneePostalCode',
        'consignor_country_code' => 'consignorCountryCode',
        'consignor_postal_code' => 'consignorPostalCode',
        'delivery_date_options' => 'deliveryDateOptions',
        'include_external_delivery_dates' => 'includeExternalDeliveryDates',
        'limit' => 'limit',
        'locale' => 'locale',
        'number_of_processing_days' => 'numberOfProcessingDays',
        'shipment_parameters' => 'shipmentParameters',
        'sorting_model' => 'sortingModel',
        'tags' => 'tags',
        'token' => 'token'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'consignee_country_code' => 'setConsigneeCountryCode',
        'consignee_postal_code' => 'setConsigneePostalCode',
        'consignor_country_code' => 'setConsignorCountryCode',
        'consignor_postal_code' => 'setConsignorPostalCode',
        'delivery_date_options' => 'setDeliveryDateOptions',
        'include_external_delivery_dates' => 'setIncludeExternalDeliveryDates',
        'limit' => 'setLimit',
        'locale' => 'setLocale',
        'number_of_processing_days' => 'setNumberOfProcessingDays',
        'shipment_parameters' => 'setShipmentParameters',
        'sorting_model' => 'setSortingModel',
        'tags' => 'setTags',
        'token' => 'setToken'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'consignee_country_code' => 'getConsigneeCountryCode',
        'consignee_postal_code' => 'getConsigneePostalCode',
        'consignor_country_code' => 'getConsignorCountryCode',
        'consignor_postal_code' => 'getConsignorPostalCode',
        'delivery_date_options' => 'getDeliveryDateOptions',
        'include_external_delivery_dates' => 'getIncludeExternalDeliveryDates',
        'limit' => 'getLimit',
        'locale' => 'getLocale',
        'number_of_processing_days' => 'getNumberOfProcessingDays',
        'shipment_parameters' => 'getShipmentParameters',
        'sorting_model' => 'getSortingModel',
        'tags' => 'getTags',
        'token' => 'getToken'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const TAGS_PACK_STATION = 'PACK_STATION';
    const TAGS_SAME_DAY = 'SAME_DAY';
    const TAGS_FLEX_DELIVERY = 'FLEX_DELIVERY';
    const TAGS_CASH_ON_DELIVERY = 'CASH_ON_DELIVERY';
    const TAGS_INSURANCE = 'INSURANCE';
    const TAGS_SIGNATURE_REQUIRED = 'SIGNATURE_REQUIRED';
    const TAGS_AT_NEIGHBOURS = 'AT_NEIGHBOURS';
    const TAGS_NOT_AT_NEIGHBOURS = 'NOT_AT_NEIGHBOURS';
    const TAGS_RETURN_ON_FAILURE = 'RETURN_ON_FAILURE';
    const TAGS_DATE_PREFERENCE = 'DATE_PREFERENCE';
    const TAGS_TWENTYFOUR_SEVEN = 'TWENTYFOUR_SEVEN';
    const TAGS_NOTIFY_RECEIVER = 'NOTIFY_RECEIVER';
    const TAGS_SUNDAY_SORTING = 'SUNDAY_SORTING';
    const TAGS_AGE_CHECK = 'AGE_CHECK';
    const TAGS_ID_CHECK = 'ID_CHECK';
    const TAGS_CLIMATE_COMPENSATION = 'CLIMATE_COMPENSATION';
    const TAGS_DANGEROUS_GOODS = 'DANGEROUS_GOODS';
    const TAGS_RETURN_TO_SENDER = 'RETURN_TO_SENDER';
    const TAGS_NO_PROOF_OF_DELIVERY = 'NO_PROOF_OF_DELIVERY';
    const TAGS_PERISHABLE = 'PERISHABLE';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTagsAllowableValues()
    {
        return [
            self::TAGS_PACK_STATION,
            self::TAGS_SAME_DAY,
            self::TAGS_FLEX_DELIVERY,
            self::TAGS_CASH_ON_DELIVERY,
            self::TAGS_INSURANCE,
            self::TAGS_SIGNATURE_REQUIRED,
            self::TAGS_AT_NEIGHBOURS,
            self::TAGS_NOT_AT_NEIGHBOURS,
            self::TAGS_RETURN_ON_FAILURE,
            self::TAGS_DATE_PREFERENCE,
            self::TAGS_TWENTYFOUR_SEVEN,
            self::TAGS_NOTIFY_RECEIVER,
            self::TAGS_SUNDAY_SORTING,
            self::TAGS_AGE_CHECK,
            self::TAGS_ID_CHECK,
            self::TAGS_CLIMATE_COMPENSATION,
            self::TAGS_DANGEROUS_GOODS,
            self::TAGS_RETURN_TO_SENDER,
            self::TAGS_NO_PROOF_OF_DELIVERY,
            self::TAGS_PERISHABLE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['consignee_country_code'] = isset($data['consignee_country_code']) ? $data['consignee_country_code'] : null;
        $this->container['consignee_postal_code'] = isset($data['consignee_postal_code']) ? $data['consignee_postal_code'] : null;
        $this->container['consignor_country_code'] = isset($data['consignor_country_code']) ? $data['consignor_country_code'] : null;
        $this->container['consignor_postal_code'] = isset($data['consignor_postal_code']) ? $data['consignor_postal_code'] : null;
        $this->container['delivery_date_options'] = isset($data['delivery_date_options']) ? $data['delivery_date_options'] : null;
        $this->container['include_external_delivery_dates'] = isset($data['include_external_delivery_dates']) ? $data['include_external_delivery_dates'] : null;
        $this->container['limit'] = isset($data['limit']) ? $data['limit'] : null;
        $this->container['locale'] = isset($data['locale']) ? $data['locale'] : null;
        $this->container['number_of_processing_days'] = isset($data['number_of_processing_days']) ? $data['number_of_processing_days'] : null;
        $this->container['shipment_parameters'] = isset($data['shipment_parameters']) ? $data['shipment_parameters'] : null;
        $this->container['sorting_model'] = isset($data['sorting_model']) ? $data['sorting_model'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['token'] = isset($data['token']) ? $data['token'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['consignee_country_code'] === null) {
            $invalidProperties[] = "'consignee_country_code' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets consignee_country_code
     *
     * @return string
     */
    public function getConsigneeCountryCode()
    {
        return $this->container['consignee_country_code'];
    }

    /**
     * Sets consignee_country_code
     *
     * @param string $consignee_country_code The [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) code for the country the shipment is being sent to.  Example: `consigneeCountryCode:\"NL\"`
     *
     * @return $this
     */
    public function setConsigneeCountryCode($consignee_country_code)
    {
        $this->container['consignee_country_code'] = $consignee_country_code;

        return $this;
    }

    /**
     * Gets consignee_postal_code
     *
     * @return string|null
     */
    public function getConsigneePostalCode()
    {
        return $this->container['consignee_postal_code'];
    }

    /**
     * Sets consignee_postal_code
     *
     * @param string|null $consignee_postal_code The postal code of the address the shipment is being sent to. The code is used to get a more precise list of available shipping options.  Example: `consigneePostalCode:\"1020HD\"`
     *
     * @return $this
     */
    public function setConsigneePostalCode($consignee_postal_code)
    {
        $this->container['consignee_postal_code'] = $consignee_postal_code;

        return $this;
    }

    /**
     * Gets consignor_country_code
     *
     * @return string|null
     */
    public function getConsignorCountryCode()
    {
        return $this->container['consignor_country_code'];
    }

    /**
     * Sets consignor_country_code
     *
     * @param string|null $consignor_country_code The [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) code for the country the shipment is being sent from.  If left empty, Paazl will use the default setting in your Paazl web app account under *Settings>Account>My address book>Sender address>Country.*  Example: `consignorCountryCode:\"NL\"`
     *
     * @return $this
     */
    public function setConsignorCountryCode($consignor_country_code)
    {
        $this->container['consignor_country_code'] = $consignor_country_code;

        return $this;
    }

    /**
     * Gets consignor_postal_code
     *
     * @return string|null
     */
    public function getConsignorPostalCode()
    {
        return $this->container['consignor_postal_code'];
    }

    /**
     * Sets consignor_postal_code
     *
     * @param string|null $consignor_postal_code The postal code of the address the shipment is being sent from. The code is used to get delivery dates from carriers if they offer this service.  If left empty, Paazl will use the default setting in your Paazl web app account under *Settings>Account>My addres book>Sender address>Postal code*.  Example: `consignorPostalCode:\"1019HD\"`
     *
     * @return $this
     */
    public function setConsignorPostalCode($consignor_postal_code)
    {
        $this->container['consignor_postal_code'] = $consignor_postal_code;

        return $this;
    }

    /**
     * Gets delivery_date_options
     *
     * @return \OpenAPI\Client\Model\DeliveryDateOptions|null
     */
    public function getDeliveryDateOptions()
    {
        return $this->container['delivery_date_options'];
    }

    /**
     * Sets delivery_date_options
     *
     * @param \OpenAPI\Client\Model\DeliveryDateOptions|null $delivery_date_options delivery_date_options
     *
     * @return $this
     */
    public function setDeliveryDateOptions($delivery_date_options)
    {
        $this->container['delivery_date_options'] = $delivery_date_options;

        return $this;
    }

    /**
     * Gets include_external_delivery_dates
     *
     * @return bool|null
     */
    public function getIncludeExternalDeliveryDates()
    {
        return $this->container['include_external_delivery_dates'];
    }

    /**
     * Sets include_external_delivery_dates
     *
     * @param bool|null $include_external_delivery_dates Gets delivery dates directly from the carrier if the carrier supplies them.  The default value is `false`.  Example: `includeExternalDeliveryDates:true`
     *
     * @return $this
     */
    public function setIncludeExternalDeliveryDates($include_external_delivery_dates)
    {
        $this->container['include_external_delivery_dates'] = $include_external_delivery_dates;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return int|null
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param int|null $limit The maximum number of shipping options that Paazl must return.  Minimum value: 1  Maximum value: 99  Example: `limit:10`
     *
     * @return $this
     */
    public function setLimit($limit)
    {
        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale Specifies the language in which the widget is displayed as well as the localized shipping option names you have configured in your web app account (under *Settings>Paazl Perfect>Shipping options*).  `locale` is specified using the format `{language}_{country}`, where `{language}` is an [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) language code and `{country}` is an [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) country code.  Example: `locale:\"fr_FR\"`
     *
     * @return $this
     */
    public function setLocale($locale)
    {
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets number_of_processing_days
     *
     * @return int|null
     */
    public function getNumberOfProcessingDays()
    {
        return $this->container['number_of_processing_days'];
    }

    /**
     * Sets number_of_processing_days
     *
     * @param int|null $number_of_processing_days The number of days a warehouse needs to get an order ready for pick-up by a carrier.   The default value is `0`. However, if you have specified a value for processing days in your webshop's [delivery matrix](https://support.paazl.com/hc/en-us/articles/360007580074-Configuring-your-delivery-matrix-), that value will override `numberOfProcessingDays`.  Minimum value: `0`  Maximum value: `99`  Example: `numberOfProcessingDays:5`
     *
     * @return $this
     */
    public function setNumberOfProcessingDays($number_of_processing_days)
    {
        $this->container['number_of_processing_days'] = $number_of_processing_days;

        return $this;
    }

    /**
     * Gets shipment_parameters
     *
     * @return \OpenAPI\Client\Model\ShipmentParameters|null
     */
    public function getShipmentParameters()
    {
        return $this->container['shipment_parameters'];
    }

    /**
     * Sets shipment_parameters
     *
     * @param \OpenAPI\Client\Model\ShipmentParameters|null $shipment_parameters shipment_parameters
     *
     * @return $this
     */
    public function setShipmentParameters($shipment_parameters)
    {
        $this->container['shipment_parameters'] = $shipment_parameters;

        return $this;
    }

    /**
     * Gets sorting_model
     *
     * @return \OpenAPI\Client\Model\SortingModel|null
     */
    public function getSortingModel()
    {
        return $this->container['sorting_model'];
    }

    /**
     * Sets sorting_model
     *
     * @param \OpenAPI\Client\Model\SortingModel|null $sorting_model sorting_model
     *
     * @return $this
     */
    public function setSortingModel($sorting_model)
    {
        $this->container['sorting_model'] = $sorting_model;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags Codes that are used to filter the shipping options that Paazl returns for display.  Example: `tags:[\"CASH_ON_DELIVERY\",\"INSURANCE\"]`
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $allowedValues = $this->getTagsAllowableValues();
        if (!is_null($tags) && array_diff($tags, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'tags', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets token
     *
     * @return string|null
     */
    public function getToken()
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string|null $token The access token returned by the `token` endpoint.  If you assign token a value, Paazl temporarily registers session details in its database in order to keep track of the choices made by webshop customers.  Example: `token:\"4f7c7af4-a379-4d5e-8ccf-807f4ba97a52\"`
     *
     * @return $this
     */
    public function setToken($token)
    {
        $this->container['token'] = $token;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


