<?php
/**
 * ShopOrderShipping
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API introduction
 *
 * ### URL for API requests  `https://api.paazl.com/`  ### Optional keys  Some of the optional key-value pairs have a default value. Where this is the case, the default values will be indicated.  You can leave out optional keys from requests. If you leave out an optional key, it will not be included in the response concerned.  ### Paazl authentication  Paazl uses a three-legged OAuth 2.0 authentication process in which the API Secret (private key) is only known to the webshop. Webshop customers never have access to that key. However, they do have access the API Key (public key). See the online help article titled \"Authentication & Authorization\" for an explanation of how to generate these keys in the Paazl web app.  In Swagger, you authorize a call using the Authorize button. After clicking this button, you enter a string with either the format \"Bearer api_key\" or the format \"Bearer api_key:api_secret\" depending on the endpoint method concerned.  #### Calls requiring \"Bearer api_key\":  &#8226; POST shippingOptions  &#8226; POST pickupLocations  &#8226; POST checkout  Example:`\"Bearer sI3flYhflh\"`   #### Calls requiring \"Bearer api_key:api_secret\":  &#8226; POST token  &#8226; GET checkout  &#8226; POST order  &#8226; PUT order  &#8226; PATCH order  &#8226; DELETE order  Example:`\"Bearer sI3flYhflh:sdHlHkyunLKsoI94luilIlndD\"`
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ShopOrderShipping Class Doc Comment
 *
 * @category Class
 * @description Contains information on the shipping option selected by a customer.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShopOrderShipping implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShopOrderShipping';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'option' => 'string',
        'pickup_location' => '\OpenAPI\Client\Model\ShopOrderPickupLocation',
        'contract' => 'string',
        'return_contract' => 'string',
        'package_count' => 'int',
        'multi_package_shipment' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'option' => null,
        'pickup_location' => null,
        'contract' => null,
        'return_contract' => null,
        'package_count' => 'int32',
        'multi_package_shipment' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'option' => 'option',
        'pickup_location' => 'pickupLocation',
        'contract' => 'contract',
        'return_contract' => 'returnContract',
        'package_count' => 'packageCount',
        'multi_package_shipment' => 'multiPackageShipment'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'option' => 'setOption',
        'pickup_location' => 'setPickupLocation',
        'contract' => 'setContract',
        'return_contract' => 'setReturnContract',
        'package_count' => 'setPackageCount',
        'multi_package_shipment' => 'setMultiPackageShipment'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'option' => 'getOption',
        'pickup_location' => 'getPickupLocation',
        'contract' => 'getContract',
        'return_contract' => 'getReturnContract',
        'package_count' => 'getPackageCount',
        'multi_package_shipment' => 'getMultiPackageShipment'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['option'] = isset($data['option']) ? $data['option'] : null;
        $this->container['pickup_location'] = isset($data['pickup_location']) ? $data['pickup_location'] : null;
        $this->container['contract'] = isset($data['contract']) ? $data['contract'] : null;
        $this->container['return_contract'] = isset($data['return_contract']) ? $data['return_contract'] : null;
        $this->container['package_count'] = isset($data['package_count']) ? $data['package_count'] : null;
        $this->container['multi_package_shipment'] = isset($data['multi_package_shipment']) ? $data['multi_package_shipment'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['option'] === null) {
            $invalidProperties[] = "'option' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets option
     *
     * @return string
     */
    public function getOption()
    {
        return $this->container['option'];
    }

    /**
     * Sets option
     *
     * @param string $option A shipping option's Paazl code. You will find a list of the identifiers of the shipping options available to your webshop in your webshop account under *Settings>Account>Overview of shipping options*.  Example: `option:\"AVG\"`
     *
     * @return $this
     */
    public function setOption($option)
    {
        $this->container['option'] = $option;

        return $this;
    }

    /**
     * Gets pickup_location
     *
     * @return \OpenAPI\Client\Model\ShopOrderPickupLocation|null
     */
    public function getPickupLocation()
    {
        return $this->container['pickup_location'];
    }

    /**
     * Sets pickup_location
     *
     * @param \OpenAPI\Client\Model\ShopOrderPickupLocation|null $pickup_location pickup_location
     *
     * @return $this
     */
    public function setPickupLocation($pickup_location)
    {
        $this->container['pickup_location'] = $pickup_location;

        return $this;
    }

    /**
     * Gets contract
     *
     * @return string|null
     */
    public function getContract()
    {
        return $this->container['contract'];
    }

    /**
     * Sets contract
     *
     * @param string|null $contract The identification code of your carrier contract for an outbound shipment.  **Note!** If you don't have this code, contact [Paazl Customer Support](mailto:support@paazl.com).  Example: `contract:\"XYZ123\"`
     *
     * @return $this
     */
    public function setContract($contract)
    {
        $this->container['contract'] = $contract;

        return $this;
    }

    /**
     * Gets return_contract
     *
     * @return string|null
     */
    public function getReturnContract()
    {
        return $this->container['return_contract'];
    }

    /**
     * Sets return_contract
     *
     * @param string|null $return_contract The identification code of your carrier contract for a return shipment.  **Note!** If you don't have this code, contact [Paazl Customer Support](mailto:support@paazl.com).  Example: `returnContract:\"321ZYX\"`
     *
     * @return $this
     */
    public function setReturnContract($return_contract)
    {
        $this->container['return_contract'] = $return_contract;

        return $this;
    }

    /**
     * Gets package_count
     *
     * @return int|null
     */
    public function getPackageCount()
    {
        return $this->container['package_count'];
    }

    /**
     * Sets package_count
     *
     * @param int|null $package_count The number of packages in a shipment.  **Note!** If `multiPackageShipment` is set to `true`, the default value of `packageCount` will be `2`.  Example: `packageCount:3`
     *
     * @return $this
     */
    public function setPackageCount($package_count)
    {
        $this->container['package_count'] = $package_count;

        return $this;
    }

    /**
     * Gets multi_package_shipment
     *
     * @return bool|null
     */
    public function getMultiPackageShipment()
    {
        return $this->container['multi_package_shipment'];
    }

    /**
     * Sets multi_package_shipment
     *
     * @param bool|null $multi_package_shipment If `true`, Paazl will treat the shipment as consolidated.  This setting affects how the packages in the shipment are numbered on its labels. The number of packages in a shipment is indicated by `packageCount`. So, for example, if `multiPackageShipment` is `true` and `packageCount` is `3`, then the labels will be numbered 1/3, 2/3, 3/3.  **Note!** If `packageCount` > `1`, then the default value of `multiPackageShipment` will be `true`. If you don't want Paazl to treat a multi-package shipment as consolidated, you have to set `multiPackageShipment` to `false`.  Example: `multiPackageShipment:false`
     *
     * @return $this
     */
    public function setMultiPackageShipment($multi_package_shipment)
    {
        $this->container['multi_package_shipment'] = $multi_package_shipment;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


